###
@local_ip = 127.0.0.1

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdF9uYW1lIjoiTWF2ZXJpY2siLCJsYXN0X25hbWUiOiJRaWFuIiwicGFzc3dvcmQiOiIkMmIkMTAkYnd4dkRCQTlpLzB6by9Xd295ZGVDLmZROTRSaUd1MnBLenM1SGpzM3F6TFZhRjZmOUZmUVcifSwiaWF0IjoxNjU2MzU4MjQ3fQ.Yavg1Pq4U_Y3xNwuSZz1hWgliNMexN73fjxdQNxXB8c

@user_id = 1
@product_id = 1
@order_id = 1

# * Hello world
GET http://{{local_ip}}:3000/

###
# * create an User
# @name loginAdmin
POST http://{{local_ip}}:3000/users/register HTTP/1.1
content-type: application/json

{
    "first_name": "Maverick",
    "last_name": "Qian",
    "password": "980620"
}

###
# * Users index
GET http://{{local_ip}}:3000/users HTTP/1.1
authorization: Bearer {{token}}

###
# * show an User
GET http://{{local_ip}}:3000/users/{{user_id}} HTTP/1.1
authorization: Bearer {{token}}

###
# * delete an User
DELETE http://{{local_ip}}:3000/users/{{user_id}} HTTP/1.1
authorization: Bearer {{token}}

###
# * Products index
GET http://{{local_ip}}:3000/products HTTP/1.1
authorization: Bearer {{token}}

###
# * show a product
GET http://{{local_ip}}:3000/products/{{product_id}} HTTP/1.1
authorization: Bearer {{token}}

###
# * create a product
POST http://{{local_ip}}:3000/products/ HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json

{
    "name": "iph",
    "price": 1000,
    "category": "ph"
}

###
# * select by category
GET http://{{local_ip}}:3000/products/category/ph HTTP/1.1
authorization: Bearer {{token}}

###
# * Orders index
GET http://{{local_ip}}:3000/orders HTTP/1.1
authorization: Bearer {{token}}

###
# * show an Order
GET http://{{local_ip}}:3000/orders/{{order_id}} HTTP/1.1
authorization: Bearer {{token}}

###
# * create an Order
POST http://{{local_ip}}:3000/orders/ HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json

{
    "user_id": {{user_id}},
    "status": "active"
}

###
# * get orders by user_id
GET http://{{local_ip}}:3000/orders/user/{{user_id}} HTTP/1.1
authorization: Bearer {{token}}

###
# * update the order
PUT http://{{local_ip}}:3000/orders/update HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json

{
    "order_id": {{order_id}},
    "status": "closed"
}

###
# * create an order_product
POST http://{{local_ip}}:3000/orders/order-product HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json

{
    "order_id": {{order_id}},
    "product_id": {{product_id}},
    "quantity": 3
}

###
# * get order_products by order_id
GET http://{{local_ip}}:3000/orders/order-product/1 HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json



###
# * delete the order_product
DELETE http://{{local_ip}}:3000/orders/order-product/{{order_id}} HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json

###
# * update the order_product
PUT http://{{local_ip}}:3000/orders/order-product/update HTTP/1.1
authorization: Bearer {{token}}
content-type: application/json

{
    "order_id": {{order_id}},
    "product_id": {{product_id}},
    "quantity": 5
}